"""Shared runtime dependencies.

The catalogue and the embedding model are expensive to construct and immutable
once loaded, so they are built once at startup rather than per request. Both are
held here instead of in module globals scattered across services, so tests can
substitute them cleanly.
"""

import logging

from app.adapters.llm.base import LLMProvider
from app.core.config import get_settings
from app.core.errors import CatalogueNotReady
from app.services.catalogue import Catalogue

logger = logging.getLogger(__name__)

_catalogue: Catalogue | None = None
_provider: LLMProvider | None = None
_taxonomy: dict | None = None


def load_taxonomy() -> dict | None:
    """The catalogue's availability map, served to the planner.

    Generated by scripts/build_taxonomy.py from the catalogue itself, so what
    the planner is told exists always matches what retrieval can actually find.
    """
    global _taxonomy
    import json

    from app.core.config import DATA_DIR

    path = DATA_DIR / "taxonomy.json"
    if not path.exists():
        logger.warning("No taxonomy at %s; run scripts/build_taxonomy.py.", path)
        _taxonomy = None
        return None
    _taxonomy = json.loads(path.read_text())
    empty = len(_taxonomy.get("coverage", {}).get("empty", []))
    logger.info("Taxonomy loaded: %d empty subcategories", empty)
    return _taxonomy


def get_taxonomy() -> dict | None:
    return _taxonomy


def load_catalogue() -> Catalogue | None:
    global _catalogue
    try:
        _catalogue = Catalogue.load()
        logger.info(
            "Catalogue loaded: %d products, embeddings=%s",
            len(_catalogue),
            _catalogue.has_vectors,
        )
    except CatalogueNotReady as exc:
        logger.error("%s", exc)
        _catalogue = None
    return _catalogue


def load_provider() -> LLMProvider | None:
    """Build the configured LLM provider, if its key is set.

    `settings.llm_provider` picks the adapter; both implement the same
    `LLMProvider` protocol, so nothing downstream of this function needs to
    know which one is live. Returns None rather than raising when the
    selected provider's key is missing: the app is designed to run without
    one, in a clearly-labelled degraded mode.
    """
    global _provider
    settings = get_settings()

    if settings.llm_provider == "local":
        # No key check: Ollama's local server doesn't need one. A missing or
        # unreachable server surfaces as LLMUnavailable on the first call and
        # degrades normally, same as any other transport failure.
        from app.adapters.llm.local_provider import LocalProvider

        _provider = LocalProvider(base_url=settings.local_llm_base_url, timeout_s=settings.llm_timeout_s)
        logger.info("LLM provider ready (local, interpret=%s)", settings.interpret_model)
        return _provider

    if settings.llm_provider == "openrouter":
        if not settings.openrouter_api_key:
            logger.warning(
                "llm_provider=openrouter but no OPENROUTER_API_KEY set; "
                "running with keyword interpretation."
            )
            _provider = None
            return None
        from app.adapters.llm.openrouter_provider import OpenRouterProvider

        _provider = OpenRouterProvider(settings.openrouter_api_key, settings.llm_timeout_s)
        logger.info("LLM provider ready (openrouter, interpret=%s)", settings.interpret_model)
        return _provider

    if not settings.anthropic_api_key:
        logger.warning("No ANTHROPIC_API_KEY set; running with keyword interpretation.")
        _provider = None
        return None
    from app.adapters.llm.anthropic_provider import AnthropicProvider

    _provider = AnthropicProvider(settings.anthropic_api_key, settings.llm_timeout_s)
    logger.info("LLM provider ready (anthropic, interpret=%s)", settings.interpret_model)
    return _provider


def get_catalogue() -> Catalogue:
    if _catalogue is None:
        raise CatalogueNotReady()
    return _catalogue


def peek_catalogue() -> Catalogue | None:
    """The catalogue if it loaded, or None -- without raising.

    `get_catalogue()` is the request path and must fail loudly. Readiness
    reporting needs the opposite: to observe that the catalogue is missing and
    say so, which is not an error condition for the probe itself.
    """
    return _catalogue


def get_provider() -> LLMProvider | None:
    return _provider
