"""Shared runtime dependencies.

The catalogue and the embedding model are expensive to construct and immutable
once loaded, so they are built once at startup rather than per request. Both are
held here instead of in module globals scattered across services, so tests can
substitute them cleanly.
"""

import logging

from app.adapters.llm.base import LLMProvider
from app.core.config import get_settings
from app.core.errors import CatalogueNotReady
from app.services.catalogue import Catalogue

logger = logging.getLogger(__name__)

_catalogue: Catalogue | None = None
_provider: LLMProvider | None = None
_taxonomy: dict | None = None


def load_taxonomy() -> dict | None:
    """The catalogue's availability map, served to the planner.

    Generated by scripts/build_taxonomy.py from the catalogue itself, so what
    the planner is told exists always matches what retrieval can actually find.
    """
    global _taxonomy
    import json

    from app.core.config import DATA_DIR

    path = DATA_DIR / "taxonomy.json"
    if not path.exists():
        logger.warning("No taxonomy at %s; run scripts/build_taxonomy.py.", path)
        _taxonomy = None
        return None
    _taxonomy = json.loads(path.read_text())
    empty = len(_taxonomy.get("coverage", {}).get("empty", []))
    logger.info("Taxonomy loaded: %d empty subcategories", empty)
    return _taxonomy


def get_taxonomy() -> dict | None:
    return _taxonomy


def load_catalogue() -> Catalogue | None:
    global _catalogue
    try:
        _catalogue = Catalogue.load()
        logger.info(
            "Catalogue loaded: %d products, embeddings=%s",
            len(_catalogue),
            _catalogue.has_vectors,
        )
    except CatalogueNotReady as exc:
        logger.error("%s", exc)
        _catalogue = None
    return _catalogue


def load_embedder() -> None:
    """Warm the query embedder so the first real search does not pay for it.

    `get_embedder()` is `lru_cache`d, so calling it here populates the cache
    that `recommend.py` reads later. Without this the ~7s sentence-transformers
    load happened lazily inside the first search -- measured as a 22.6s first
    request against a 7.5s warm one -- and on a fresh deploy it is worse still,
    because the ~90MB model downloads from Hugging Face on first use.

    Deliberately never raises: `get_embedder()` already degrades to the hashing
    embedder rather than failing, and a container that refuses to boot is worse
    than one serving weaker matches with `degraded_mode` set.
    """
    try:
        from app.adapters.embeddings.local import get_embedder

        embedder = get_embedder()
        logger.info(
            "Embedder ready: %s (%dd, semantic=%s)",
            embedder.name,
            embedder.dimension,
            embedder.is_semantic,
        )
    except Exception as exc:  # noqa: BLE001 - startup must survive any failure
        logger.warning("Embedder warm-up failed (%s); it will load on first search.", exc)


def _build_named_provider(name: str, settings) -> LLMProvider | None:
    """Construct one provider by name, or None if its key is missing.

    Shared by the primary and fallback slots so the anthropic/openrouter/local
    branching lives in exactly one place.
    """
    if name == "local":
        # No key check: Ollama's local server doesn't need one. A missing or
        # unreachable server surfaces as LLMUnavailable on the first call and
        # degrades normally, same as any other transport failure.
        from app.adapters.llm.local_provider import LocalProvider

        return LocalProvider(base_url=settings.local_llm_base_url, timeout_s=settings.llm_timeout_s)

    if name == "openrouter":
        if not settings.openrouter_api_key:
            return None
        from app.adapters.llm.openrouter_provider import OpenRouterProvider

        return OpenRouterProvider(settings.openrouter_api_key, settings.llm_timeout_s)

    if not settings.anthropic_api_key:
        return None
    from app.adapters.llm.anthropic_provider import AnthropicProvider

    return AnthropicProvider(settings.anthropic_api_key, settings.llm_timeout_s)


def load_provider() -> LLMProvider | None:
    """Build the configured LLM provider (plus an optional fallback), if
    either has its key set.

    `settings.llm_provider` picks the primary adapter; every adapter (and the
    two-provider `FallbackProvider` wrapper) implements the same `LLMProvider`
    protocol, so nothing downstream of this function needs to know which one
    is actually live. Returns None only when neither primary nor fallback has
    a usable key: the app is designed to run without one, in a
    clearly-labelled degraded mode.
    """
    global _provider
    settings = get_settings()

    primary = _build_named_provider(settings.llm_provider, settings)
    if primary is not None:
        logger.info(
            "LLM provider ready (%s, interpret=%s)", settings.llm_provider, settings.interpret_model
        )

    fallback = None
    if settings.llm_fallback_provider and settings.llm_fallback_provider != settings.llm_provider:
        if not settings.fallback_interpret_model:
            logger.warning(
                "llm_fallback_provider=%s set but fallback_interpret_model is missing; "
                "fallback disabled.",
                settings.llm_fallback_provider,
            )
        else:
            fallback = _build_named_provider(settings.llm_fallback_provider, settings)
            if fallback is not None:
                logger.info(
                    "Fallback LLM provider ready (%s, interpret=%s)",
                    settings.llm_fallback_provider,
                    settings.fallback_interpret_model,
                )
            else:
                logger.warning(
                    "llm_fallback_provider=%s set but its key is missing; fallback disabled.",
                    settings.llm_fallback_provider,
                )

    if fallback is not None:
        # Wrapped even when primary is None: recommend.py always calls
        # provider.structured(model=settings.interpret_model, ...), so a bare
        # fallback provider would be called with the *primary's* model id --
        # the same provider/model mismatch fixed elsewhere this session.
        # FallbackProvider ignores that argument and uses each hop's own model.
        from app.adapters.llm.fallback_provider import FallbackProvider

        chain = [(fallback, settings.fallback_interpret_model)]
        if primary is not None:
            chain.insert(0, (primary, settings.interpret_model))
        _provider = FallbackProvider(chain, earlier_hop_timeout_s=settings.fallback_after_s)
        return _provider

    _provider = primary
    if _provider is None:
        logger.warning("No LLM provider configured; running with keyword interpretation.")
    return _provider


def get_catalogue() -> Catalogue:
    if _catalogue is None:
        raise CatalogueNotReady()
    return _catalogue


def peek_catalogue() -> Catalogue | None:
    """The catalogue if it loaded, or None -- without raising.

    `get_catalogue()` is the request path and must fail loudly. Readiness
    reporting needs the opposite: to observe that the catalogue is missing and
    say so, which is not an error condition for the probe itself.
    """
    return _catalogue


def get_provider() -> LLMProvider | None:
    return _provider
